# Generated by Django 3.2.16 on 2024-11-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_group_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='posts.post'),
        ),
    ]
