# Generated by Django 3.2.16 on 2024-11-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20241112_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
