# Generated by Django 3.2.16 on 2024-11-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_follow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
