# Generated by Django 3.2.16 on 2024-11-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20241113_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
