# Generated by Django 3.2.16 on 2024-11-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_alter_follow_following'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_following',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_user_following',
        ),
    ]
