# Generated by Django 3.2.16 on 2024-11-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_alter_follow_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={},
        ),
    ]
